# Hand annotations: tier (doubles viability in M-C, value of best form) + notes
T = {}
def t(tier, names, note=None):
    for n in names.split('|'):
        T[n.strip()] = [tier, note]

# S / A / B / C / D
t('S','Rillaboom|Sneasler|Incineroar')
t('S','Floette-Eternal')
t('A','Salamence|Golisopod|Farigiraf|Kingambit|Indeedee-F|Basculegion|Garchomp|Charizard|Archaludon|Gholdengo|Pelipper|Raichu|Milotic')
t('A','Whimsicott|Arcanine-Hisui|Gardevoir|Staraptor|Tyranitar|Lucario|Dragonite|Sylveon|Politoed')
t('B','Grimmsnarl|Sinistcha|Torkoal|Excadrill|Volcarona|Armarouge|Indeedee|Kommo-o|Gengar|Froslass|Metagross|Swampert|Absol|Baxcalibur|Mawile|Annihilape|Ceruledge|Primarina|Aerodactyl|Venusaur|Delphox|Pawmot|Corviknight|Glimmora|Blastoise|Meowstic-F|Snorlax|Scrafty|Hawlucha|Aegislash|Pyroar|Talonflame|Dragapult|Kangaskhan|Ninetales-Alola|Scizor|Slowbro|Maushold|Blaziken|Rotom-Wash|Sableye|Hatterene')
t('C','Hydreigon|Alakazam|Lopunny|Clefable|Meganium|Camerupt|Gallade|Typhlosion-Hisui|Espathra|Sirfetch’d|Pincurchin|Inteleon|Altaria|Tsareena|Scovillain|Mamoswine|Empoleon|Malamar|Grapploct|Arcanine|Gyarados|Krookodile|Tinkaton|Azumarill|Palafin|Medicham|Greninja|Starmie|Mimikyu|Meowstic|Liepard|Rotom-Heat|Rotom-Mow|Klefki|Overqwil|Audino|Dragalge|Feraligatr|Weavile|Chandelure|Conkeldurr|Reuniclus|Squawkabilly|Gliscor|Eelektross|Manectric|Golurk|Ninetales|Araquanid|Skarmory|Cinderace|Salazzle|Oranguru|Vivillon|Mr. Rime|Toxicroak|Mr. Mime|Heliolisk|Lycanroc-Dusk|Garganacl|Wyrdeer|Persian-Alola|Victreebel|Slowking|Slowbro-Galar|Slowking-Galar|Chesnaught|Crabominable|Drampa|Hippowdon|Rhyperior|Florges|Aromatisse|Noivern|Emboar|Scolipede|Falinks|Barbaracle|Sceptile|Houndoom|Banette|Chimecho|Pidgeot|Sharpedo|Heracross|Pinsir|Abomasnow|Steelix|Ampharos|Glalie|Aggron|Beedrill|Decidueye-Hisui|Qwilfish|Tauros-Paldea-Aqua|Tauros-Paldea-Blaze|Tauros-Paldea-Combat|Morpeko|Rotom-Fan|Rotom|Bellibolt|Clawitzer|Luxray|Mabosstiff|Diggersby|Hydrapple|Kleavor|Leafeon|Arboliva|Zoroark-Hisui|Typhlosion|Toxtricity|Quaquaval|Samurott-Hisui|Vileplume|Umbreon|Pangoro|Machamp|Tauros|Arbok|Wigglytuff|Simipour|Simisear|Simisage|Musharna|Cofagrigus|Runerigus|Polteageist|Spiritomb|Goodra-Hisui|Rotom-Frost|Jolteon|Espeon|Vaporeon|Glaceon|Flareon|Raichu-Alola|Alcremie|Slurpuff|Gourgeist|Trevenant|Mudsdale|Torterra|Bastiodon|Avalugg|Avalugg-Hisui|Stunfisk-Galar|Stunfisk|Dedenne|Emolga|Pikachu|Gogoat|Thievul|Lycanroc|Passimian|Orthworm|Houndstone|Serperior|Skeledirge|Ditto|Toxapex|Vanilluxe|Aurorus|Tyrantrum|Rampardos|Goodra|Beartic|Decidueye|Flapple|Appletun|Castform|Forretress|Furfrou|Lycanroc-Midnight|Sandaconda|Samurott|Garbodor|Watchog|Toucannon|Farfetch’d|Swalot|Persian|Perrserker|Ariados|Zoroark|Leafeon')

# Demote clearly weak ones to D
for n in 'Ditto|Castform|Furfrou|Watchog|Farfetch’d|Swalot|Garbodor|Ariados|Toucannon|Persian|Sandaconda|Flapple|Appletun|Beartic|Rampardos|Tyrantrum|Vanilluxe|Aurorus|Glaceon|Flareon|Vaporeon|Jolteon|Espeon|Umbreon|Lycanroc-Midnight|Lycanroc|Orthworm|Houndstone|Thievul|Gogoat|Samurott|Decidueye|Serperior|Skeledirge|Pikachu|Emolga|Avalugg|Avalugg-Hisui|Bastiodon|Stunfisk|Musharna|Cofagrigus|Runerigus|Polteageist|Spiritomb|Trevenant|Gourgeist|Slurpuff|Goodra|Zoroark|Perrserker|Glalie|Beedrill|Pidgeot|Banette|Simisear|Simisage|Dedenne|Forretress|Mudsdale|Torterra|Wigglytuff|Machamp|Pangoro|Typhlosion|Vileplume|Rotom-Frost|Alcremie|Toxapex|Leafeon|Chimecho|Ampharos|Steelix|Abomasnow|Heracross|Pinsir|Sharpedo|Houndoom|Sceptile|Barbaracle|Falinks|Scolipede|Emboar|Noivern|Aggron|Kleavor|Hydrapple|Diggersby|Arboliva|Goodra-Hisui|Raichu-Alola|Mabosstiff|Toxtricity|Quaquaval|Samurott-Hisui|Luxray|Clawitzer'.split('|'):
    T[n][0] = 'D'
# a few cheap D->C overrides kept as C because of a real niche
for n in 'Arbok|Tauros|Morpeko|Rotom|Rotom-Fan|Simipour|Stunfisk-Galar|Bellibolt|Heliolisk|Toxicroak|Mr. Mime|Mr. Rime|Squawkabilly|Gliscor|Decidueye-Hisui|Qwilfish|Tauros-Paldea-Combat|Garganacl|Persian-Alola|Wyrdeer|Passimian':
    pass

N = {
'Charizard': 'Two Megas in one pick. Mega Y (Drought, 159 SpA) is the format\'s premier special Mega (96% of Charizard use Charizardite Y): sun Heat Wave/Weather Ball/Solar Beam. Mega X (Fire/Dragon, Tough Claws, 130 Atk) is a Dragon Dance sweeper that does not care about weather and resists Fire/Grass/Water/Electric/Bug/Steel/Fairy — a niche surprise option vs Fairy-light teams. Proven alongside Pelipper ("Sun-Rain", Lexicon, Grand Champions Festival Encore, July 2026). Weak to Rock Slide (4x as Y).',
'Sinistcha': 'Grass/Ghost bulky support: Hospitality heals partner on entry, Rage Powder redirection, Trick Room, Matcha Gotcha (spread Grass, heals, burn chance), Life Dew, Strength Sap. Immune to Fake Out and Normal/Fighting. Usage 7.4% (rank 25). Common items Sitrus/Leftovers/Colbur. Partners: Incineroar, Tyranitar, Milotic, Golisopod.',
'Pelipper': 'Drizzle rain setter with Tailwind, Wide Guard, Icy Wind, U-turn, Hurricane (100% in rain), Weather Ball. 12% usage; Pelipper + Archaludon and Pelipper + Charizard-Y (Sun-Rain) are proven cores. 4x Electric weak.',
'Kangaskhan': 'Base: Fake Out + Inner Focus/Scrappy, bulky Normal. Mega (Parental Bond: every attack hits twice, second hit 25%): Fake Out that hits twice (breaks Sash), Double-Edge/Body Slam, Sucker Punch, Drain Punch/Low Kick, Ice Punch, EQ. Low ladder usage in M-C; competes with your Charizard for the one Mega slot.',
'Rillaboom': 'Most-used mon (35%). Grassy Surge + Fake Out + Grassy Glide priority + Wood Hammer/High Horsepower; enables Grassy Seed users (Sneasler Unburden, Gholdengo).',
'Sneasler': '#2 usage (32%). Fake Out, Unburden + terrain seed, Close Combat/Dire Claw (30% status in Champions), Coaching, Quick Guard. Fighting/Poison.',
'Incineroar': 'Fake Out + Intimidate + Parting Shot + Flare Blitz/Knock Off/Throat Chop; the best support in the game.',
'Floette-Eternal': 'Mega Floette (Fairy, Fairy Aura, 155 SpA/148 SpD/102 Spe) — tier-1 Mega, on 2026 World Championship-winning team (Takuma Yamazaki). Dazzling Gleam/Moonblast/Light of Ruin/Calm Mind/Draining Kiss.',
'Salamence': 'Intimidate base; Mega (Aerilate, Flying-type Double-Edge/Hyper Voice, 120 Spe) is the defining new M-C Mega (core with Rillaboom/Sneasler on ~12–20% of teams). Dragon Dance.',
'Golisopod': 'Emergency Exit pivot; First Impression; Mega Golisopod (Tough Claws) new in M-C. Very common on TR and rain-adjacent teams. Bug/Water.',
'Farigiraf': 'Armor Tail (blocks priority incl. Fake Out on its side), Trick Room, Hyper Voice, Helping Hand; top TR setter.',
'Kingambit': 'Defiant (punishes Intimidate), Supreme Overlord, Sucker Punch, Kowtow Cleave, Swords Dance; best check to Basculegion and Psychic spam.',
'Basculegion': 'Last Respects + Adaptability/Swift Swim; Wave Crash/Aqua Jet; Ghost immune to Fake Out. Male (Atk) is the physical one.',
'Basculegion-F': 'Female form: Special attacker (Adaptability/Swift Swim), Last Respects is physical so it is weaker than male; still rain abuser. Species clause shared with male.',
'Garchomp': 'Best Ground type; two Megas: Mega Garchomp (Rough Skin, Sand Force? no—Mega uses Sand Force in SV; check) and Mega Garchomp Z (Levitate, 151 Spe — fastest tier). EQ/Dragon Claw/Rock Slide.',
'Archaludon': 'Stamina + Electro Shot (instant in rain) + Body Press; Pelipper partner. Steel/Dragon.',
'Gholdengo': 'Good as Gold blocks status/support moves; Make It Rain nerfed (−2 SpA, 95% acc) but Nasty Plot + Grassy Seed sets thrive. Immune to Fake Out and Sneasler\'s moves.',
'Raichu': 'Mega Raichu Y (No Guard, 160 SpA, 130 Spe) one of the most-used Megas (on 4 of 10 recent winning teams); Mega Raichu X (Electric Surge, physical). Base has Fake Out.',
'Milotic': 'Competitive punishes Intimidate; Recover, Icy Wind, Scald/Muddy Water; bulky water.',
'Whimsicott': 'Prankster Tailwind, Encore, Moonblast, Sunny Day; staple speed control.',
'Arcanine-Hisui': 'Intimidate, Rock Head Head Smash/Rock Slide, Flare Blitz, Extreme Speed; anti-Charizard/Mence/Baxcalibur.',
'Gardevoir': 'Mega Gardevoir (Pixilate Hyper Voice, 165 SpA) core of Psychic Spam with Indeedee.',
'Staraptor': 'Mega Staraptor (Contrary Close Combat/Brave Bird) — big M-B/M-C Mega, Worlds 2026 top Mega usage.',
'Tyranitar': 'Sand Stream; Mega Tyranitar; Rock Slide/Knock Off/Dragon Dance; sand core with Excadrill.',
'Lucario': 'Two Megas: Mega Lucario (Adaptability) and Mega Lucario Z (Aura Guard, 151 Spe). Fake Out? no (check). Close Combat/Flash Cannon/Extreme Speed.',
'Dragonite': 'Multiscale; Mega Dragonite (Multiscale) on 2026 Worlds-winning team; Extreme Speed, Tailwind.',
'Politoed': 'Drizzle rain setter #2 (bulkier, Perish Song, Icy Wind, Helping Hand).',
'Indeedee-F': 'Psychic Surge + Follow Me + Trick Room + Helping Hand; blocks priority in terrain. 20% usage.',
'Indeedee': 'Male: Psychic Surge offensive version (Expanding Force); appears on winning Mega Gardevoir teams.',
'Grimmsnarl': 'Prankster screens (Reflect/Light Screen/Light Clay), Parting Shot, Thunder Wave, Fake Tears.',
'Torkoal': 'Drought + Eruption; slowest TR attacker (base 20).',
'Excadrill': 'Sand Rush; Mega Excadrill (Piercing Drill: contact hits through Protect for 1/4).',
'Volcarona': 'Quiver Dance, Heat Wave, Rage Powder; beats Kingambit/Rillaboom/Sneasler/Gholdengo.',
'Armarouge': 'Trick Room + Expanding Force/Heat Wave + Wide Guard; Psychic Spam piece.',
'Gengar': 'Mega Gengar (Shadow Tag, 170 SpA) Perish trap; won Alpensee Tour #74.',
'Froslass': 'Mega Froslass (Snow Warning, 140 SpA, 120 Spe) Blizzard in snow; anti-Salamence.',
'Metagross': 'Mega Metagross (Tough Claws, 110 Spe).',
'Swampert': 'Mega Swampert (Swift Swim, 150 Atk) premium rain sweeper.',
'Absol': 'Two Megas: Mega Absol (Magic Bounce) and Mega Absol Z (Sharpness, 151 Spe); Sucker Punch, Night Slash/Psycho Cut slicing.',
'Baxcalibur': 'Mega Baxcalibur (Thermal Exchange, 175 Atk); Glaive Rush, Icicle Crash. Snow abuser.',
'Mawile': 'Intimidate base; Mega Mawile (Huge Power) — good vs Salamence/snow.',
'Annihilape': 'Rage Fist, Bulk Up, Final Gambit; Fighting/Ghost, immune to Fake Out.',
'Ceruledge': 'Bitter Blade, Poltergeist, Shadow Sneak; Fire/Ghost; on Sitrus-Series #78 and Unova #14 winning teams.',
'Primarina': 'Liquid Voice Hyper Voice (spread Water); good vs Mence/Baxcalibur.',
'Aerodactyl': 'Mega Aerodactyl (Tough Claws, 150 Spe), Tailwind, Rock Slide, Wide Guard.',
'Venusaur': 'Chlorophyll sun sweeper; Mega Venusaur (Thick Fat) bulky. Sleep Powder.',
'Delphox': 'Mega Delphox (Levitate, 159 SpA, 134 Spe), Nasty Plot, Heat Wave/Psychic.',
'Pawmot': 'Fake Out? (Champions learnset: check) Double Shock, Close Combat, Revival Blessing.',
'Scrafty': 'Intimidate + Fake Out + Coaching + Quick Guard + Snarl; Mega Scrafty (Intimidate). Classic support.',
'Hawlucha': 'Mega Hawlucha (No Guard) won Thursday Night Throwdown #4. Unburden + seed.',
'Aegislash': 'Stance Change, King\'s Shield (returns in Champions), Wide Guard; Life Orb sets beat psyspam.',
'Pyroar': 'Mega Pyroar (Fire Mane: ×1.5 Fire) — on London Corviknights Weekly 15 winning team.',
'Talonflame': 'Gale Wings priority Tailwind/Brave Bird (at full HP).',
'Snorlax': 'Trick Room tank/attacker; Belly Drum? check; won Alpensee Tour #74 (with Mega Gengar) and TNT #4.',
'Meowstic-F': 'Fake Out? / Trick Room / screens; Competitive; Mega Meowstic (Trace).',
'Meowstic': 'Prankster screens/Thunder Wave/Quick Guard, Fake Out, Trick Room; Mega Meowstic (Trace).',
'Squawkabilly': 'Budget support: Intimidate + Tailwind + Parting Shot + Fake Tears + Helping Hand + Taunt. Frail (51/51 defences).',
'Tinkaton': 'Fake Out + Gigaton Hammer + Encore/Thunder Wave; Steel/Fairy answers Dragons and Kingambit.',
'Azumarill': 'Huge Power Aqua Jet/Liquidation/Play Rough, Belly Drum; rain-boosted; Fairy answer to Dragons.',
'Toxicroak': 'Fake Out + Dry Skin (heals in rain, immune to Water) + Coaching/Quick Guard + Sucker Punch/Close Combat. Great cheap rain-team support.',
'Heliolisk': 'Dry Skin (heals in rain) or Solar Power (sun), Electroweb, Thunder (100% acc in rain), Weather Ball, Shed Tail; 109 Spe. Weather-flexible budget attacker.',
'Mr. Mime': 'Fake Out + Wide Guard + Quick Guard + Trick Room + screens; Psychic/Fairy; very frail (40 HP).',
'Mr. Rime': 'Fake Out + Trick Room + Icy Wind + screens; Ice/Psychic.',
'Decidueye-Hisui': 'Tailwind + Scrappy Close Combat/Triple Arrows + Coaching; Grass/Fighting.',
'Gliscor': 'Tailwind + Poison Heal + EQ/Knock Off; Ground/Flying (Electric immune).',
'Qwilfish': 'Intimidate OR Swift Swim; Liquidation/Waterfall in rain, Taunt, Thunder Wave.',
'Arbok': 'Cheapest Intimidate (2 pts) with Snarl? / Glare? (check); Poison.',
'Tauros': 'Intimidate (2 pts), Sheer Force; Normal. Species clause with all Paldean Tauros.',
'Tauros-Paldea-Combat': 'Intimidate Fighting (3 pts), Raging Bull/Close Combat.',
'Tauros-Paldea-Aqua': 'Intimidate Fighting/Water; Wave Crash/Raging Bull; rain-boosted.',
'Tauros-Paldea-Blaze': 'Intimidate Fighting/Fire.',
'Mabosstiff': 'Intimidate (or Guard Dog: Intimidate boosts it); Dark; Snarl/Taunt.',
'Luxray': 'Intimidate + Electroweb + Snarl; Wild Charge/Thunder in rain.',
'Bellibolt': 'Electromorphosis + Thunder (100% in rain), Electroweb; bulky Electric.',
'Rotom-Fan': 'Levitate, Electroweb, Will-O-Wisp, Thunder Wave; Electric/Flying. One Rotom per team.',
'Rotom': 'Base Rotom (Electric/Ghost, immune to Fake Out), Electroweb, Will-O-Wisp, Thunder in rain. One Rotom per team.',
'Morpeko': 'Fake Out + Parting Shot + Electroweb + Aura Wheel; 2 pts.',
'Persian-Alola': 'Fake Out + Parting Shot + Snarl + Icy Wind; Fur Coat; Dark.',
'Simipour': 'Fake Out (1 pt) Water; rain Hydro Pump.',
'Garganacl': 'Salt Cure, Wide Guard, Purifying Salt; huge physical bulk; TR-friendly.',
'Wyrdeer': 'Intimidate + Trick Room + Hyper Voice; Normal/Psychic.',
'Conkeldurr': 'Trick Room attacker: Guts/Iron Fist Mach Punch, Drain Punch, Wide Guard.',
'Stunfisk-Galar': 'Bulky Steel/Ground, Mimicry; Thunder Wave, Yawn; Electric-immune via Ground.',
'Diggersby': 'Huge Power Earthquake/High Horsepower; Normal/Ground; 6 pts.',
'Passimian': 'Receiver/Defiant, Coaching, Quick Guard, Electroweb.',
'Clawitzer': 'Mega Launcher Water Pulse/Aura Sphere/Dark Pulse/Dragon Pulse; rain abuser.',
'Hydreigon': 'Tailwind + Snarl + Draco/Dark Pulse; Levitate.',
'Arcanine': 'Intimidate + Snarl + Will-O-Wisp + Extreme Speed; Fire.',
'Gyarados': 'Intimidate + Dragon Dance; Mega Gyarados (Mold Breaker, Water/Dark).',
'Medicham': 'Mega Medicham (Pure Power) Fake Out + Trick Room.',
'Liepard': 'Prankster + Fake Out + Encore/Taunt/Snarl/Fake Tears; Dark (Prankster fails vs Dark).',
'Klefki': 'Prankster screens/Thunder Wave; Steel/Fairy.',
'Sableye': 'Prankster + Fake Out; Mega Sableye (Magic Bounce).',
'Audino': 'Mega Audino (Healer, Fairy/Normal); Heal Pulse, Trick Room? (check), Helping Hand.',
'Overqwil': 'Intimidate/Swift Swim; Dark/Poison.',
'Corviknight': 'Mirror Armor (blocks Intimidate), Tailwind, U-turn, Body Press.',
'Rotom-Wash': 'Levitate Hydro Pump/Volt Switch/Will-O-Wisp; rain-friendly.',
'Rotom-Heat': 'Levitate Overheat/Will-O-Wisp; sun-friendly.',
'Rotom-Mow': 'Levitate Leaf Storm.',
'Krookodile': 'Intimidate + Moxie, Ground/Dark, Knock Off/EQ.',
'Infernape': 'Fake Out + Close Combat; fast Fire.',
'Dragapult': 'Fastest non-Mega (142), Tailwind/Will-O-Wisp/Dragon Darts.',
'Ninetales-Alola': 'Snow Warning + Aurora Veil + Icy Wind; Ice/Fairy.',
'Empoleon': 'Steel/Water; Icy Wind, Flip Turn?; Competitive? (check).',
'Grimmsnarl ': '',
'Scizor': 'Technician Bullet Punch; Mega Scizor.',
'Blastoise': 'Mega Blastoise (Mega Launcher) Shell Smash + Water Spout/Pulse; rain abuser.',
'Glimmora': 'Mega Glimmora (Adaptability), Toxic Debris; Rock coverage.',
'Kommo-o': 'Clangorous Soul (never misses in Champions), Bulletproof/Soundproof; Coaching.',
'Ninetales': 'Drought backup sun setter; Encore/Will-O-Wisp/Heat Wave.',
'Hatterene': 'Magic Bounce Trick Room setter, Expanding Force.',
'Talonflame ': '',
'Maushold': 'Friend Guard support / Population Bomb; Follow Me (check) — Technician.',
'Blaziken': 'Speed Boost; Mega Blaziken.',
'Lopunny': 'Mega Lopunny (Scrappy, Fake Out).',
'Starmie': 'Mega Starmie (Huge Power, 120 Spe).',
'Clefable': 'Follow Me + Friend Guard? ; Mega Clefable (Magic Bounce, Fairy/Flying).',
'Meganium': 'Mega Meganium (Mega Sol: acts as if Sun).',
'Camerupt': 'Mega Camerupt (Sheer Force) Eruption TR.',
'Slowbro': 'Mega Slowbro (Shell Armor) TR tank; won TNT #4.',
'Feraligatr': 'Mega Feraligatr (Dragonize) Dragon Dance.',
'Greninja': 'Mega Greninja (Protean).',
'Chandelure': 'Mega Chandelure (Infiltrator, 175 SpA) Trick Room/Heat Wave.',
'Altaria': 'Mega Altaria (Pixilate) Hyper Voice; Tailwind; Cloud Nine base.',
'Scovillain': 'Mega Scovillain (Spicy Spray), Rage Powder.',
'Eelektross': 'Mega Eelektross (Eelevate).',
'Manectric': 'Mega Manectric (Intimidate, 135 Spe).',
'Golurk': 'Mega Golurk (Unseen Fist).',
'Dragalge': 'Mega Dragalge (Regenerator).',
'Chesnaught': 'Mega Chesnaught (Bulletproof); Wide Guard.',
'Drampa': 'Mega Drampa (Berserk).',
'Crabominable': 'Mega Crabominable (Iron Fist), Wide Guard.',
'Malamar': 'Mega Malamar (Contrary) Superpower; Trick Room.',
'Barbaracle': 'Mega Barbaracle (Tough Claws).',
'Falinks': 'Mega Falinks (Defiant).',
'Scolipede': 'Mega Scolipede (Shell Armor).',
'Pinsir': 'Mega Pinsir (Aerilate).',
'Heracross': 'Mega Heracross (Skill Link).',
'Steelix': 'Mega Steelix (Sand Force).',
'Ampharos': 'Mega Ampharos (Mold Breaker).',
'Aggron': 'Mega Aggron (Filter).',
'Houndoom': 'Mega Houndoom (Solar Power).',
'Sharpedo': 'Mega Sharpedo (Strong Jaw).',
'Pidgeot': 'Mega Pidgeot (No Guard), Tailwind.',
'Beedrill': 'Mega Beedrill (Adaptability).',
'Glalie': 'Mega Glalie (Refrigerate).',
'Banette': 'Mega Banette (Prankster).',
'Chimecho': 'Mega Chimecho (Levitate); Trick Room/screens.',
'Gallade': 'Mega Gallade; Wide Guard/Trick Room/Sharpness.',
'Alakazam': 'Mega Alakazam (Trace, 150 Spe).',
'Abomasnow': 'Snow Warning; Mega Abomasnow; Aurora Veil.',
'Sceptile': 'Mega Sceptile (Lightning Rod).',
'Emboar': 'Mega Emboar (Mold Breaker).',
'Victreebel': 'Chlorophyll + Sleep Powder; Mega Victreebel (Innards Out).',
'Vivillon': 'Rage Powder + Sleep Powder + Tailwind + Friend Guard? (Compound Eyes Hurricane).',
'Oranguru': 'Instruct? / Trick Room / Inner Focus.',
'Reuniclus': 'Magic Guard TR attacker.',
'Pincurchin': 'Electric Surge setter (base 15 Spe); Rising Voltage.',
}
N.update({
'Garchomp': 'Best Ground type (16.8%). Two Megas: Mega Garchomp (Dragon/Ground, Sand Force, 170 Atk, 92 Spe) and Mega Garchomp Z (pure Dragon, Levitate, 141 SpA/130 Atk, 151 Spe — top speed tier; won Chadweezy95 Ep 22). EQ/Dragon Claw/Rock Slide/Stomping Tantrum.',
'Lucario': 'Two Megas: Mega Lucario (Adaptability, 145 Atk/140 SpA, 112 Spe) and Mega Lucario Z (Aura Guard: halves contact damage; 164 SpA, 151 Spe; won Intimidators Challenge 10-01). No Fake Out in Champions. Extreme Speed, Vacuum Wave, Bullet Punch, Close Combat, Meteor Mash.',
'Pawmot': 'Fake Out + Revival Blessing + Double Shock + Close Combat + Mach Punch + Nuzzle; Iron Fist boosts Double Shock (punch flag in Champions). 105 Spe.',
'Snorlax': 'Trick Room attacker/tank: Belly Drum, Curse, Yawn, High Horsepower, Heat Crash; Thick Fat/Gluttony. On Alpensee Tour #74 (Mega Gengar) and Thursday Night Throwdown #4 winning teams.',
'Meowstic-F': 'Fake Out + Trick Room + Competitive; Mega Meowstic (Trace).',
'Arbok': 'Cheapest Intimidate (2 pts) with Glare (paralysis), Snarl, Sucker Punch, Knock Off, Coil, Gunk Shot.',
'Audino': 'Mega Audino (Healer, Fairy/Normal). Heal Pulse, Life Dew, Trick Room, Helping Hand (no Follow Me in Champions).',
'Empoleon': 'Steel/Water: Competitive (punishes Intimidate), Icy Wind, Flip Turn, Surf, Flash Cannon, Feather Dance.',
'Clefable': 'Follow Me + Life Dew + Helping Hand + Moonblast; Friend Guard/Magic Guard/Unaware; Mega Clefable (Magic Bounce, Fairy/Flying).',
'Maushold': 'Follow Me + Friend Guard + Population Bomb + Tidy Up + Feint; 111 Spe.',
'Vivillon': 'Rage Powder + Sleep Powder + Tailwind + Quiver Dance + Hurricane (Compound Eyes). Weak to Rock (4x).',
'Oranguru': 'Instruct + Trick Room + Foul Play; Inner Focus (immune to Fake Out flinch).',
'Golisopod': 'Mega Golisopod is Bug/Steel (Tough Claws, 150 Atk, 175 Def, 40 Spe) — new in M-C and the #4 most-used mon. Base: Emergency Exit pivot, First Impression. Elite Trick Room attacker.',
'Absol': 'Two Megas: Mega Absol (Dark, Magic Bounce, 115 Spe) and Mega Absol Z (Dark/Ghost, Sharpness, 154 Atk, 151 Spe — immune to Fake Out). Sucker Punch, slicing moves (Night Slash/Psycho Cut/Slash 80 BP).',
'Staraptor': 'Mega Staraptor (Fighting/Flying, Contrary, 140 Atk, 110 Spe) — Close Combat raises its defences instead of lowering them; Brave Bird. 30%+ of Worlds 2026 Megas were Staraptor/Swampert/Raichu-Y.',
'Kangaskhan': 'Base: Fake Out + Inner Focus/Scrappy + Sucker Punch, bulky Normal. Mega (Parental Bond: second hit 25%, 125 Atk, 100 Spe): double-hit Fake Out breaks Sash; Double-Edge/Body Slam, Drain Punch/Low Kick, Ice Punch, EQ, Rock Slide (no Power-Up Punch in Champions). Very low M-C ladder usage; competes with your Charizard for the one Mega slot.',
})
